import numpy as np
import pandas as pd
import os
import webbrowser
from google import genai

class AIassistant:
    def __init__(self):
        self.df = None
        self.generated_code = ""
        # IMPORTANT: Ensure your Gemini API Key is valid
        self.api_key = "AIzaSyBx8LB5t8wXU6zWGEJm8HMEGksmAYqj3PY"
        self.client = genai.Client(api_key=self.api_key)

    def load_csv(self, file_path):
        try:
            self.df = pd.read_csv(file_path)
            print(f"Loaded '{file_path}' with {self.df.shape[0]} rows.")
        except Exception as e:
            print(f"Error loading CSV: {e}")

    def get_the_prompt(self, task_description: str):
        if self.df is None:
            print("No dataset loaded.")
            return

        # Provides a high-level statistical summary for the AI to interpret trends
        preview = self.df.describe(include='all').to_string()

        prompt = f"""
        You are a Creative Web Developer and Data Storyteller.

        DATASET CONTEXT (Summary Stats):
        {preview}

        TASK: {task_description}

        REQUIREMENTS (CRITICAL):
        1. DO NOT SHOW THE DATASET VALUES OR TABLES. 
        2. CONVERT numerical trends into "Human-readable Text" narratives (e.g., "The analysis suggests a stable average across the cohort").
        3. INTEGRATE IMAGES: Use <img> tags with high-quality source URLs from LoremFlickr.
           Format: <img src="https://loremflickr.com[keyword]" 
                       class="img-fluid rounded mb-4 shadow" 
                       onerror="this.src='https://picsum.photos'; this.onerror=null;">
           (AI: Replace [keyword] with a relevant term like 'health', 'medical', or 'science' based on the data).
        4. STRUCTURE: Create a clean, modern "Data Story" webpage using Bootstrap 5 cards and sections.
        5. STYLE: Ensure a professional look with proper padding, typography, and a clean background.
        6. OUTPUT: Provide ONLY the python code that defines the variable 'html_content'. No explanation, no markdown backticks.
        """

        try:
            print("Generating Visual Story Web Page...")
            response = self.client.models.generate_content(
                model='gemini-2.5-flash', 
                contents=prompt
            )
            # Remove any potential markdown wrapping from AI response
            self.generated_code = response.text.replace("```python", "").replace("```", "").strip()
        except Exception as e:
            print(f"API Error: {e}")

    def run_code(self):
        if not self.generated_code:
            print("No code available. Check your API quota or key.")
            return

        local_env = {'df': self.df, 'pd': pd, 'np': np}

        try:
            # Execute the code generated by the AI to define 'html_content'
            exec(self.generated_code, local_env)
            
            if 'html_content' in local_env:
                file_name = "data_story.html"
                with open(file_name, "w", encoding="utf-8") as f:
                    f.write(local_env['html_content'])
                
                full_path = os.path.realpath(file_name)
                print(f"Success! Visual Web Page saved at: {full_path}")
                webbrowser.open('file://' + full_path)
            else:
                print("Error: The AI-generated code did not define 'html_content'.")
        except Exception as e:
            print(f"Execution Error: {e}")

# --- EXECUTION ---
if __name__ == "__main__":
    bot = AIassistant()
    # Path to your local CSV file
    path = r"C:\python\python webinnor\dataset.csv" 
    
    bot.load_csv(path)
    
    # Prompt focusing on human-readable storytelling and working visual imagery
    bot.get_the_prompt("Create a professional visual story web page with text summaries and beautiful images. Hide all raw numbers.")
    bot.run_code()
